version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - network
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  nginx:
    platform: linux/amd64
    image: limjung99/nginx
    hostname: nginx
    build: ./nginx/
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - network

  backend:
    platform: linux/amd64
    image: limjung99/gachi
    build: ./app/
    volumes:
      - .:/code
    networks:
      - network
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
    command:  sh -c "
            python manage.py makemigrations authentication&&
            python manage.py makemigrations friend&&
            python manage.py makemigrations image&&
            python manage.py makemigrations trip&&
            python manage.py migrate&&
            gunicorn --bind 0.0.0.0:8000 gachi_backend.wsgi:application"

networks:
  network: