# Generated by Django 4.2 on 2023-09-30 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_tripinvite'),
        ('image', '0002_alter_tripimage_upload_date_alter_tripimage_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripimage',
            name='users',
        ),
        migrations.AlterField(
            model_name='tripimage',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='trip.trip'),
        ),
    ]
