# Generated by Django 4.2 on 2023-09-03 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='owner',
        ),
    ]
